var data =
[
	{"kanji":"上","reading":"うえ","meaning":"cima","level":"B2"},
	{"kanji":"下","reading":"した","meaning":"baixo","level":"B2"},
	{"kanji":"中","reading":"なか","meaning":"dentro","level":"B2"},
	{"kanji":"人","reading":"ひと","meaning":"pessoa","level":"B2"},
	{"kanji":"体","reading":"からだ","meaning":"corpo","level":"B4"},
	{"kanji":"兄","reading":"あに","meaning":"irmão mais velho (próprio)","level":"B2"},
	{"kanji":"先","reading":"さき","meaning":"anterior","level":"B2"},
	{"kanji":"冬","reading":"ふゆ","meaning":"inverno","level":"B3"},
	{"kanji":"前","reading":"まえ","meaning":"frente","level":"B2"},
	{"kanji":"北","reading":"きた","meaning":"norte","level":"B3"},
	{"kanji":"南","reading":"みなみ","meaning":"sul","level":"B3"},
	{"kanji":"口","reading":"くち","meaning":"boca","level":"B3"},
	{"kanji":"台","reading":"だい","meaning":"suporte","level":"B4"},
	{"kanji":"右","reading":"みぎ","meaning":"direita","level":"B2"},
	{"kanji":"品","reading":"しな","meaning":"artigo (mercadoria)","level":"B4"},
	{"kanji":"図","reading":"ず","meaning":"gráfico","level":"B4"},
	{"kanji":"国","reading":"くに","meaning":"país","level":"B3"},
	{"kanji":"夏","reading":"なつ","meaning":"verão","level":"B3"},
	{"kanji":"外","reading":"そと","meaning":"fora","level":"B2"},
	{"kanji":"夜","reading":"よる","meaning":"noite","level":"B3"},
	{"kanji":"女","reading":"おんな","meaning":"mulher","level":"B2"},
	{"kanji":"妹","reading":"いもうと","meaning":"irmã mais nova (própria)","level":"B2"},
	{"kanji":"姉","reading":"あね","meaning":"irmã mais velh (própria)","level":"B2"},
	{"kanji":"子","reading":"こ","meaning":"criança; filhote","level":"B2"},
	{"kanji":"字","reading":"じ","meaning":"letra","level":"B3"},
	{"kanji":"家","reading":"いえ","meaning":"casa","level":"B3"},
	{"kanji":"左","reading":"ひだり","meaning":"esquerda","level":"B2"},
	{"kanji":"年","reading":"とし","meaning":"ano","level":"B2"},
	{"kanji":"店","reading":"みせ","meaning":"loja","level":"B2"},
	{"kanji":"弟","reading":"おとうと","meaning":"irmão mais novo (próprio)","level":"B2"},
	{"kanji":"後","reading":"あと","meaning":"depois","level":"B2"},
	{"kanji":"所","reading":"ところ","meaning":"lugar","level":"B4"},
	{"kanji":"手","reading":"て","meaning":"mão","level":"B3"},
	{"kanji":"方","reading":"かた","meaning":"pessoa (forma polida)","level":"B4"},
	{"kanji":"旅","reading":"たび","meaning":"jornada (viagem)","level":"B3"},
	{"kanji":"春","reading":"はる","meaning":"primavera","level":"B3"},
	{"kanji":"昼","reading":"ひる","meaning":"tarde","level":"B3"},
	{"kanji":"時","reading":"とき","meaning":"tempo; vez","level":"B4"},
	{"kanji":"服","reading":"ふく","meaning":"roupa","level":"B4"},
	{"kanji":"朝","reading":"あさ","meaning":"manhã","level":"B3"},
	{"kanji":"本","reading":"ほん","meaning":"livro","level":"B2"},
	{"kanji":"村","reading":"むら","meaning":"aldeia","level":"B4"},
	{"kanji":"東","reading":"ひがし","meaning":"leste","level":"B3"},
	{"kanji":"林","reading":"はやし","meaning":"bosque; mata","level":"B4"},
	{"kanji":"森","reading":"もり","meaning":"floresta","level":"B4"},
	{"kanji":"業","reading":"わざ","meaning":"trabalho; obra; feito","level":"B4"},
	{"kanji":"楽","reading":"らく","meaning":"conforto; prazer","level":"B3"},
	{"kanji":"横","reading":"よこ","meaning":"lado","level":"B2"},
	{"kanji":"歌","reading":"うた","meaning":"canção","level":"B4"},
	{"kanji":"母","reading":"はは","meaning":"mãe (própria)","level":"B2"},
	{"kanji":"海","reading":"うみ","meaning":"mar","level":"B2"},
	{"kanji":"父","reading":"ちち","meaning":"pai (próprio)","level":"B2"},
	{"kanji":"牛","reading":"うし","meaning":"vaca","level":"B4"},
	{"kanji":"物","reading":"もの","meaning":"coisa","level":"B3"},
	{"kanji":"生","reading":"なま","meaning":"cru","level":"B2"},
	{"kanji":"用","reading":"よう","meaning":"afazeres","level":"B3"},
	{"kanji":"男","reading":"おとこ","meaning":"homem","level":"B2"},
	{"kanji":"町","reading":"まち","meaning":"cidade","level":"B4"},
	{"kanji":"白","reading":"しろ","meaning":"branco (cor)","level":"B2"},
	{"kanji":"百","reading":"ひゃく","meaning":"cem","level":"B2"},
	{"kanji":"目","reading":"め","meaning":"olho","level":"B3"},
	{"kanji":"私","reading":"わたし","meaning":"eu","level":"B3","other_readings":["わたくし"]},
	{"kanji":"秋","reading":"あき","meaning":"outono","level":"B3"},
	{"kanji":"空","reading":"そら","meaning":"céu","level":"B3"},
	{"kanji":"紙","reading":"かみ","meaning":"papel","level":"B4"},
	{"kanji":"者","reading":"もの","meaning":"pessoa; indivíduo","level":"B4"},
	{"kanji":"耳","reading":"みみ","meaning":"orelha","level":"B3"},
	{"kanji":"肉","reading":"にく","meaning":"carne","level":"B4"},
	{"kanji":"色","reading":"いろ","meaning":"cortar","level":"B4"},
	{"kanji":"花","reading":"はな","meaning":"flor","level":"B2"},
	{"kanji":"薬","reading":"くすり","meaning":"remédio","level":"B3"},
	{"kanji":"西","reading":"にし","meaning":"oeste","level":"B3"},
	{"kanji":"赤","reading":"あか","meaning":"vermelho (cor)","level":"B2"},
	{"kanji":"足","reading":"あし","meaning":"perna; pé","level":"B3"},
	{"kanji":"車","reading":"くるま","meaning":"carro","level":"B2"},
	{"kanji":"運","reading":"うん","meaning":"sorte; sina","level":"B3"},
	{"kanji":"道","reading":"みち","meaning":"caminho","level":"B3"},
	{"kanji":"都","reading":"みやこ","meaning":"cidade grande; capital","level":"B4"},
	{"kanji":"銀","reading":"ぎん","meaning":"prata (metal)","level":"B4"},
	{"kanji":"間","reading":"あいだ","meaning":"entre (prep.)","level":"B2"},
	{"kanji":"雨","reading":"あめ","meaning":"chuva","level":"B3"},
	{"kanji":"青","reading":"あお","meaning":"azul (cor)","level":"B2"},
	{"kanji":"頭","reading":"あたま","meaning":"cabeça","level":"B3"},
	{"kanji":"顔","reading":"かお","meaning":"rosto","level":"B3"},
	{"kanji":"飯","reading":"めし","meaning":"arroz cozido; comida (uso masculino)","level":"B4"},
	{"kanji":"首","reading":"くび","meaning":"pescoço","level":"B3"},
	{"kanji":"駅","reading":"えき","meaning":"estação","level":"B2"},
	{"kanji":"魚","reading":"さかな","meaning":"peixe","level":"B3"},
	{"kanji":"鳥","reading":"とり","meaning":"pássaro; ave","level":"B4"},
	{"kanji":"黒","reading":"くろ","meaning":"preto (cor)","level":"B2"},
	{"kanji":"お兄さん","reading":"おにいさん","meaning":"irmão mais velho (de outra pessoa)","level":"B2"},
	{"kanji":"お土産","reading":"おみやげ","meaning":"lembrancinha","level":"B4"},
	{"kanji":"お姉さん","reading":"おねえさん","meaning":"irmãa mais velha (de outra pessoa)","level":"B2"},
	{"kanji":"お母さん","reading":"おかあさん","meaning":"mãe (de outra pessoa)","level":"B2"},
	{"kanji":"お父さん","reading":"おとうさん","meaning":"pai (de outra pessoa)","level":"B2"},
	{"kanji":"お茶","reading":"おちゃ","meaning":"chá","level":"B4"},
	{"kanji":"ご飯","reading":"ごはん","meaning":"arroz cozido; comida","level":"B4"},
	{"kanji":"ローマ字","reading":"ローマじ","meaning":"letra romanizada","level":"B3"},
	{"kanji":"一万","reading":"いちまん","meaning":"dez mil","level":"B2"},
	{"kanji":"一万円","reading":"いちまんえん","meaning":"dez mil ienes","level":"B2"},
	{"kanji":"一世","reading":"いっせい","meaning":"primeira geração","level":"B3"},
	{"kanji":"一人","reading":"ひとり","meaning":"uma pessoa","level":"B2"},
	{"kanji":"一千","reading":"いっせん","meaning":"mil","level":"B2"},
	{"kanji":"一回","reading":"いっかい","meaning":"uma vez","level":"B3"},
	{"kanji":"一日中","reading":"いちにちじゅう","meaning":"em um dia","level":"B2"},
	{"kanji":"一画","reading":"いっかく","meaning":"um traço (contagem para kanji)","level":"B4"},
	{"kanji":"一足","reading":"いっそく","meaning":"um par de calçados","level":"B3"},
	{"kanji":"一週間","reading":"いっしゅうかん","meaning":"uma semana","level":"B2"},
	{"kanji":"一頭","reading":"いっとう","meaning":"um [contagem de animal grande]","level":"B3"},
	{"kanji":"三万","reading":"さんまん","meaning":"trinta mil","level":"B2"},
	{"kanji":"三世","reading":"さんせい","meaning":"terceira geração","level":"B3"},
	{"kanji":"三千","reading":"さんぜん","meaning":"três mil","level":"B2"},
	{"kanji":"三百","reading":"さんびゃく","meaning":"trezentos","level":"B2"},
	{"kanji":"三足","reading":"さんぞく","meaning":"três pares de calçado","level":"B3"},
	{"kanji":"上がる","reading":"あがる","meaning":"subir","level":"B2"},
	{"kanji":"上る","reading":"のぼる","meaning":"escalar","level":"B2"},
	{"kanji":"上京する","reading":"じょうきょうする","meaning":"ir para Tóquio","level":"B4"},
	{"kanji":"上品","reading":"じょうひん","meaning":"delicado; elegante; requintado","level":"B4"},
	{"kanji":"上手","reading":"じょうず","meaning":"hábil","level":"B2"},
	{"kanji":"上映する","reading":"じょうえいする","meaning":"estar em cartaz","level":"B4"},
	{"kanji":"上着","reading":"うわぎ","meaning":"casaco","level":"B4"},
	{"kanji":"下がる","reading":"さがる","meaning":"descer","level":"B2"},
	{"kanji":"下りる","reading":"おりる","meaning":"descer (de veículo)","level":"B2"},
	{"kanji":"下る","reading":"くだる","meaning":"descer (barranco)","level":"B2"},
	{"kanji":"下品","reading":"げひん","meaning":"vulgar; indecente; grosseria","level":"B4"},
	{"kanji":"下手","reading":"へた","meaning":"inábil","level":"B2"},
	{"kanji":"下町","reading":"したまち","meaning":"centro da cidade; centro comercial","level":"B4"},
	{"kanji":"世の中","reading":"よのなか","meaning":"mundo (vida e sociedade)","level":"B3"},
	{"kanji":"世界","reading":"せかい","meaning":"mundo","level":"B3"},
	{"kanji":"中古車","reading":"ちゅうこしゃ","meaning":"carro usado","level":"B2"},
	{"kanji":"中国","reading":"ちゅうごく","meaning":"China","level":"B3"},
	{"kanji":"中国産","reading":"ちゅうごくさん","meaning":"produto da China","level":"B4"},
	{"kanji":"中止する","reading":"ちゅうしする","meaning":"cancelar","level":"B3"},
	{"kanji":"主な","reading":"おもな","meaning":"principal","level":"B4"},
	{"kanji":"主人","reading":"しゅじん","meaning":"marido; dono (de loja)","level":"B4"},
	{"kanji":"主食","reading":"しゅしょく","meaning":"alimento base","level":"B4"},
	{"kanji":"乗る","reading":"のる","meaning":"embarcar; montar; subir","level":"B4"},
	{"kanji":"乗車する","reading":"じょうしゃする","meaning":"embarcar (trem ou carro)","level":"B4"},
	{"kanji":"事務員","reading":"じむいん","meaning":"funcionário de escritório","level":"B3"},
	{"kanji":"事務所","reading":"じむしょ","meaning":"escritório","level":"B3"},
	{"kanji":"事故","reading":"じこ","meaning":"acidente","level":"B3"},
	{"kanji":"二万","reading":"にまん","meaning":"vinte mil","level":"B2"},
	{"kanji":"二千","reading":"にせん","meaning":"dois mil","level":"B2"},
	{"kanji":"二度五分","reading":"にどごぶ","meaning":"2,5º","level":"B4"},
	{"kanji":"二百","reading":"にひゃく","meaning":"duzentos","level":"B2"},
	{"kanji":"二頭","reading":"にとう","meaning":"dois [contagem de animal grande]","level":"B3"},
	{"kanji":"五円","reading":"ごえん","meaning":"cinco ienes","level":"B2"},
	{"kanji":"京都","reading":"きょうと","meaning":"Quioto","level":"B4"},
	{"kanji":"人口","reading":"じんこう","meaning":"população","level":"B3"},
	{"kanji":"今夜","reading":"こんや","meaning":"esta noite","level":"B3"},
	{"kanji":"今年","reading":"ことし","meaning":"este ano","level":"B2"},
	{"kanji":"今度","reading":"こんど","meaning":"esta vez; próxima vez","level":"B4"},
	{"kanji":"今週中","reading":"こんしゅうちゅう","meaning":"durante esta semana","level":"B2"},
	{"kanji":"仕事","reading":"しごと","meaning":"trabalho","level":"B3"},
	{"kanji":"仕入れる","reading":"しいれる","meaning":"comprar no atacado","level":"B3"},
	{"kanji":"仕方","reading":"しかた","meaning":"maneira; modo","level":"B3"},
	{"kanji":"代える","reading":"かえる","meaning":"trocar-se","level":"B3"},
	{"kanji":"代わる","reading":"かわる","meaning":"trocar-se","level":"B3"},
	{"kanji":"代表","reading":"だいひょう","meaning":"representar (país, empresa, pessoa etc)","level":"B3"},
	{"kanji":"休み","reading":"やすみ","meaning":"férias","level":"B2"},
	{"kanji":"休む","reading":"やすむ","meaning":"descansar","level":"B2"},
	{"kanji":"休憩","reading":"きゅうけい","meaning":"intervalo","level":"B2"},
	{"kanji":"休日","reading":"きゅうじつ","meaning":"feriado","level":"B2"},
	{"kanji":"会う","reading":"あう","meaning":"conhecer; encontrar","level":"B2"},
	{"kanji":"会社","reading":"かいしゃ","meaning":"companhia; empresa","level":"B2"},
	{"kanji":"会社員","reading":"かいしゃいん","meaning":"funcionário de companhia","level":"B2"},
	{"kanji":"会計","reading":"かいけい","meaning":"contabilidade","level":"B4"},
	{"kanji":"会話","reading":"かいわ","meaning":"diálogo","level":"B2"},
	{"kanji":"伝言","reading":"でんごん","meaning":"recado","level":"B4"},
	{"kanji":"住所","reading":"じゅうしょ","meaning":"endereço","level":"B4"},
	{"kanji":"体力","reading":"たいりょく","meaning":"resistência física","level":"B4"},
	{"kanji":"体重","reading":"たいじゅう","meaning":"peso corporal","level":"B4"},
	{"kanji":"何人","reading":"なんにん","meaning":"quantas pessoas","level":"B2"},
	{"kanji":"何台","reading":"なんだい","meaning":"(contagem de eletrodomésticos, carros etc)","level":"B4"},
	{"kanji":"何回","reading":"なんかい","meaning":"quantas vezes","level":"B3"},
	{"kanji":"何曜日","reading":"なんようび","meaning":"qual dia da semana","level":"B3"},
	{"kanji":"作り方","reading":"つくりかた","meaning":"modo de preparo","level":"B4"},
	{"kanji":"作る","reading":"つくる","meaning":"fazer; construir; preparar","level":"B4"},
	{"kanji":"作文","reading":"さくぶん","meaning":"redação","level":"B4"},
	{"kanji":"作業","reading":"さぎょう","meaning":"serviço","level":"B4"},
	{"kanji":"使う","reading":"つかう","meaning":"usar","level":"B4"},
	{"kanji":"使用","reading":"しよう","meaning":"utilizar","level":"B4"},
	{"kanji":"便り","reading":"たより","meaning":"notícia (como a pessoa tem passado)","level":"B4"},
	{"kanji":"便利","reading":"べんり","meaning":"prático","level":"B4"},
	{"kanji":"借りる","reading":"かりる","meaning":"tomar emprestado","level":"B4"},
	{"kanji":"借家","reading":"しゃくや","meaning":"casa de aluguel","level":"B4"},
	{"kanji":"借金","reading":"しゃっきん","meaning":"dívida","level":"B4"},
	{"kanji":"元気","reading":"げんき","meaning":"saudável","level":"B2"},
	{"kanji":"兄弟","reading":"きょうだい","meaning":"irmãos","level":"B2"},
	{"kanji":"先生","reading":"せんせい","meaning":"professor","level":"B2"},
	{"kanji":"先週","reading":"せんしゅう","meaning":"semana passada","level":"B2"},
	{"kanji":"入る","reading":"はいる","meaning":"entrar","level":"B3"},
	{"kanji":"入れる","reading":"いれる","meaning":"colocar dentro","level":"B3"},
	{"kanji":"入口","reading":"いりぐち","meaning":"entrada","level":"B3"},
	{"kanji":"入学","reading":"にゅうがく","meaning":"ingresso na escola/faculdade","level":"B3"},
	{"kanji":"入社","reading":"にゅうしゃ","meaning":"ingresso na empresa","level":"B3"},
	{"kanji":"入院する","reading":"にゅういんする","meaning":"internar-se (hospital)","level":"B3"},
	{"kanji":"六百","reading":"ろっぴゃく","meaning":"seiscentos","level":"B2"},
	{"kanji":"写す","reading":"うつす","meaning":"copiar; fotografar","level":"B4"},
	{"kanji":"写真","reading":"しゃしん","meaning":"foto","level":"B4"},
	{"kanji":"冬休み","reading":"ふゆやすみ","meaning":"férias de inverno","level":"B3"},
	{"kanji":"出かける","reading":"でかける","meaning":"sair para algum lugar","level":"B3"},
	{"kanji":"出す","reading":"だす","meaning":"tirar","level":"B3"},
	{"kanji":"出る","reading":"でる","meaning":"sair","level":"B3"},
	{"kanji":"出口","reading":"でぐち","meaning":"saída","level":"B3"},
	{"kanji":"切る","reading":"きる","meaning":"cortar","level":"B4"},
	{"kanji":"切手","reading":"きって","meaning":"selo","level":"B4"},
	{"kanji":"勉学","reading":"べんがく","meaning":"busca do conhecimento","level":"B4"},
	{"kanji":"勉強","reading":"べんきょう","meaning":"estudo","level":"B4"},
	{"kanji":"動かす","reading":"うごかす","meaning":"mover","level":"B3"},
	{"kanji":"動く","reading":"うごく","meaning":"mover-se","level":"B3"},
	{"kanji":"動物","reading":"どうぶつ","meaning":"animal","level":"B3"},
	{"kanji":"動物園","reading":"どうぶつえん","meaning":"zoológico","level":"B3"},
	{"kanji":"北区","reading":"きたく","meaning":"zona norte","level":"B4"},
	{"kanji":"北口","reading":"きたぐち","meaning":"saída norte","level":"B3"},
	{"kanji":"北海道","reading":"ほっかいどう","meaning":"Hokkaido","level":"B3"},
	{"kanji":"北部","reading":"ほくぶ","meaning":"região norte","level":"B3"},
	{"kanji":"医学","reading":"いがく","meaning":"medicina","level":"B4"},
	{"kanji":"医者","reading":"いしゃ","meaning":"médico","level":"B4"},
	{"kanji":"医院","reading":"いいん","meaning":"clínica médica","level":"B4"},
	{"kanji":"十二色","reading":"じゅうにしょく","meaning":"doze cores","level":"B4"},
	{"kanji":"十円","reading":"じゅうえん","meaning":"dez ienes","level":"B2"},
	{"kanji":"午前","reading":"ごぜん","meaning":"antes do meio-dia","level":"B2"},
	{"kanji":"午前中","reading":"ごぜんちゅう","meaning":"no período da manhã","level":"B2"},
	{"kanji":"午後","reading":"ごご","meaning":"pós meio-dia","level":"B2"},
	{"kanji":"南口","reading":"みなみぐち","meaning":"saída sul","level":"B3"},
	{"kanji":"南町","reading":"みなみちょう","meaning":"divisão sul","level":"B4"},
	{"kanji":"南米","reading":"なんべい","meaning":"América do Sul","level":"B3"},
	{"kanji":"去る","reading":"さる","meaning":"afastar-se; partir","level":"B4"},
	{"kanji":"去年","reading":"きょねん","meaning":"ano passado","level":"B4"},
	{"kanji":"友人","reading":"ゆうじん","meaning":"amigo [formal]","level":"B2"},
	{"kanji":"友達","reading":"ともだち","meaning":"amigo [usual]","level":"B2"},
	{"kanji":"古い","reading":"ふるい","meaning":"velho","level":"B2"},
	{"kanji":"台所","reading":"だいどころ","meaning":"cozinha","level":"B4"},
	{"kanji":"台風","reading":"たいふう","meaning":"tufão","level":"B4"},
	{"kanji":"名前","reading":"なまえ","meaning":"nome","level":"B3"},
	{"kanji":"和服","reading":"わふく","meaning":"roupa no estilo oriental","level":"B4"},
	{"kanji":"品物","reading":"しなもの","meaning":"mercadoria","level":"B4"},
	{"kanji":"四時","reading":"よじ","meaning":"quatro horas","level":"B4"},
	{"kanji":"四画","reading":"よんかく","meaning":"quatro traços (contagem para kanji)","level":"B4"},
	{"kanji":"回す","reading":"まわす","meaning":"girar","level":"B3"},
	{"kanji":"回る","reading":"まわる","meaning":"girar-se","level":"B3"},
	{"kanji":"図書室","reading":"としょしつ","meaning":"biblioteca (sala)","level":"B4"},
	{"kanji":"図書館","reading":"としょかん","meaning":"biblioteca (prédio)","level":"B4"},
	{"kanji":"国歌","reading":"こっか","meaning":"hino nacional","level":"B4"},
	{"kanji":"国立大学","reading":"こくりつだいがく","meaning":"faculdade nacional","level":"B3"},
	{"kanji":"土地","reading":"とち","meaning":"terreno","level":"B4"},
	{"kanji":"地下","reading":"ちか","meaning":"sub-solo","level":"B4"},
	{"kanji":"地下鉄","reading":"ちかてつ","meaning":"metrô","level":"B2"},
	{"kanji":"地区","reading":"ちく","meaning":"zona; região","level":"B4"},
	{"kanji":"地図","reading":"ちず","meaning":"mapa","level":"B4"},
	{"kanji":"場所","reading":"ばしょ","meaning":"lugar","level":"B3"},
	{"kanji":"売る","reading":"うる","meaning":"vender","level":"B2"},
	{"kanji":"売買","reading":"ばいばい","meaning":"comércio","level":"B2"},
	{"kanji":"夏休み","reading":"なつやすみ","meaning":"férias de verão","level":"B3"},
	{"kanji":"夕方","reading":"ゆうがた","meaning":"fim de tarde","level":"B4"},
	{"kanji":"外れる","reading":"はずれる","meaning":"sair do lugar","level":"B2"},
	{"kanji":"外出","reading":"がいしゅつ","meaning":"saída; passeio; excursão","level":"B3"},
	{"kanji":"外国","reading":"がいこく","meaning":"país estrangeiro","level":"B3"},
	{"kanji":"外国人","reading":"がいこくじん","meaning":"estrangeiro","level":"B3"},
	{"kanji":"外国語","reading":"がいこくご","meaning":"idioma estrangeiro","level":"B3"},
	{"kanji":"多い","reading":"おおい","meaning":"em grande quantidade","level":"B3"},
	{"kanji":"多少","reading":"多少","meaning":"um pouco","level":"B3"},
	{"kanji":"夜中","reading":"よなか","meaning":"madrugada","level":"B3"},
	{"kanji":"夜食","reading":"やしょく","meaning":"ceia","level":"B3"},
	{"kanji":"大きい","reading":"おおきい","meaning":"grande","level":"B2"},
	{"kanji":"大会","reading":"たいかい","meaning":"torneio","level":"B2"},
	{"kanji":"大切","reading":"たいせつ","meaning":"importante","level":"B4"},
	{"kanji":"大好き","reading":"だいすき","meaning":"gostar muito","level":"B2"},
	{"kanji":"大好物","reading":"だいこうぶつ","meaning":"comida favorita","level":"B2"},
	{"kanji":"大学","reading":"だいがく","meaning":"faculdade","level":"B2"},
	{"kanji":"大学院","reading":"だいがくいん","meaning":"pós-graduação","level":"B3"},
	{"kanji":"大西洋","reading":"たいせいよう","meaning":"Oceano Atlântico","level":"B4"},
	{"kanji":"大阪市","reading":"おおさかし","meaning":"Cidade de Osaka","level":"B4"},
	{"kanji":"大阪校","reading":"おおさかこう","meaning":"unidade (filial) de Osaka","level":"B2"},
	{"kanji":"大雨","reading":"おおあめ","meaning":"tempestade","level":"B3"},
	{"kanji":"天気","reading":"てんき","meaning":"tempo; clima","level":"B2"},
	{"kanji":"天気図","reading":"てんきず","meaning":"mapa meteorológico","level":"B4"},
	{"kanji":"太い","reading":"ふとい","meaning":"grosso e cilíndrico","level":"B4"},
	{"kanji":"太る","reading":"ふとる","meaning":"engordar","level":"B4"},
	{"kanji":"太平洋","reading":"たいへいよう","meaning":"Oceano Pacífico","level":"B4"},
	{"kanji":"太鼓","reading":"たいこ","meaning":"taiko","level":"B4"},
	{"kanji":"女の子","reading":"おんなのこ","meaning":"menina","level":"B2"},
	{"kanji":"女子","reading":"じょし","meaning":"menina; senhorita; feminino (banheiro)","level":"B2"},
	{"kanji":"女性","reading":"じょせい","meaning":"moça; feminino (banheiro)","level":"B2"},
	{"kanji":"好き","reading":"すき","meaning":"gostar","level":"B2"},
	{"kanji":"妹さん","reading":"いもうとさん","meaning":"irmã mais nova (de outra pessoa)","level":"B2"},
	{"kanji":"姉妹","reading":"しまい","meaning":"irmãs","level":"B2"},
	{"kanji":"始まる","reading":"はじまる","meaning":"começar; iniciar [a si mesmo]","level":"B3"},
	{"kanji":"始める","reading":"はじめる","meaning":"começar; iniciar [algo]","level":"B3"},
	{"kanji":"子供用","reading":"こどもよう","meaning":"para crianças","level":"B3"},
	{"kanji":"学ぶ","reading":"まなぶ","meaning":"aprender; estudar","level":"B2"},
	{"kanji":"学校","reading":"がっこう","meaning":"escola","level":"B2"},
	{"kanji":"学生","reading":"がくせい","meaning":"aluno","level":"B2"},
	{"kanji":"安い","reading":"やすい","meaning":"barato","level":"B2"},
	{"kanji":"安らか","reading":"やすらか","meaning":"paz; tranquilidade [contexto fúnebre]","level":"B2"},
	{"kanji":"安心","reading":"あんしん","meaning":"tranquilidade","level":"B2"},
	{"kanji":"家主","reading":"やぬし","meaning":"proprietário de imóvel","level":"B4"},
	{"kanji":"家族","reading":"かぞく","meaning":"família","level":"B4"},
	{"kanji":"家賃","reading":"やちん","meaning":"aluguel","level":"B3"},
	{"kanji":"寒い","reading":"さむい","meaning":"frio (clima)","level":"B3"},
	{"kanji":"小さい","reading":"ちいさい","meaning":"pequeno","level":"B2"},
	{"kanji":"小学校","reading":"しょうがっこう","meaning":"escola primária","level":"B2"},
	{"kanji":"小川","reading":"おがわ","meaning":"riacho","level":"B2"},
	{"kanji":"小林さん","reading":"こばやしさん","meaning":"Sr. Kobayashi","level":"B4"},
	{"kanji":"小鳥","reading":"ことり","meaning":"passarinho","level":"B4"},
	{"kanji":"少し","reading":"すこし","meaning":"pouco","level":"B3"},
	{"kanji":"少ない","reading":"すくない","meaning":"em pequena quantidade","level":"B3"},
	{"kanji":"少女","reading":"しょうじょ","meaning":"menina","level":"B3"},
	{"kanji":"少年","reading":"しょうねん","meaning":"menino","level":"B3"},
	{"kanji":"山口さん","reading":"やまぐちさん","meaning":"Sr. Yamaguchi","level":"B3"},
	{"kanji":"山本さん","reading":"やまもとさん","meaning":"Sr. Yamamoto","level":"B2"},
	{"kanji":"工場","reading":"こうじょう","meaning":"fábrica; indústria","level":"B3"},
	{"kanji":"左右","reading":"さゆう","meaning":"esquerda e direita","level":"B2"},
	{"kanji":"市場","reading":"いちば","meaning":"mercado","level":"B4"},
	{"kanji":"市長","reading":"しちょう","meaning":"prefeito","level":"B4"},
	{"kanji":"帰る","reading":"かえる","meaning":"retornar (para casa)","level":"B4"},
	{"kanji":"帰国する","reading":"きこくする","meaning":"voltar ao país de origem","level":"B4"},
	{"kanji":"広い","reading":"ひろい","meaning":"largo; amplo","level":"B2"},
	{"kanji":"広場","reading":"ひろば","meaning":"praça; largo","level":"B3"},
	{"kanji":"店員","reading":"てんいん","meaning":"lojista","level":"B2"},
	{"kanji":"建つ","reading":"たつ","meaning":"ser construído","level":"B4"},
	{"kanji":"建てる","reading":"たてる","meaning":"construir","level":"B4"},
	{"kanji":"建物","reading":"たてもの","meaning":"construção","level":"B4"},
	{"kanji":"引き出し","reading":"ひきだし","meaning":"gaveta","level":"B3"},
	{"kanji":"弟さん","reading":"おとうとさん","meaning":"irmão mais novo (de outra pessoa)","level":"B2"},
	{"kanji":"弱い","reading":"よわい","meaning":"fraco","level":"B4"},
	{"kanji":"強い","reading":"つよい","meaning":"forte","level":"B4"},
	{"kanji":"強弱","reading":"きょうじゃく","meaning":"força; intensidade","level":"B4"},
	{"kanji":"待つ","reading":"まつ","meaning":"esperar","level":"B2"},
	{"kanji":"待合室","reading":"まちあいしつ","meaning":"sala de espera","level":"B2"},
	{"kanji":"後ろ","reading":"うしろ","meaning":"atrás","level":"B2"},
	{"kanji":"思い出す","reading":"おもいだす","meaning":"lembrar; recordar","level":"B4"},
	{"kanji":"思う","reading":"おもう","meaning":"achar; pensar","level":"B4"},
	{"kanji":"急ぐ","reading":"いそぐ","meaning":"apressar-se","level":"B3"},
	{"kanji":"急に","reading":"きゅうに","meaning":"de repente","level":"B3"},
	{"kanji":"急行","reading":"きゅうこう","meaning":"trem semi-expresso","level":"B3"},
	{"kanji":"意味","reading":"いみ","meaning":"significado","level":"B3"},
	{"kanji":"意思","reading":"いし","meaning":"intenção; propósito","level":"B4"},
	{"kanji":"意見","reading":"いけん","meaning":"opinião","level":"B3"},
	{"kanji":"手紙","reading":"てがみ","meaning":"carta","level":"B4"},
	{"kanji":"手首","reading":"てくび","meaning":"pulso; punho","level":"B3"},
	{"kanji":"持つ","reading":"もつ","meaning":"segurar","level":"B3"},
	{"kanji":"接待","reading":"せったい","meaning":"recepção (para negócios)","level":"B2"},
	{"kanji":"教える","reading":"おしえる","meaning":"ensinar","level":"B2"},
	{"kanji":"教会","reading":"きょうかい","meaning":"igreja","level":"B2"},
	{"kanji":"散歩する","reading":"さんぽする","meaning":"passear a pé","level":"B4"},
	{"kanji":"料理","reading":"りょうり","meaning":"culinária","level":"B3"},
	{"kanji":"料金","reading":"りょうきん","meaning":"taxa; tarifa","level":"B3"},
	{"kanji":"新しい","reading":"あたらしい","meaning":"novo","level":"B2"},
	{"kanji":"新聞","reading":"しんぶん","meaning":"jornal","level":"B2"},
	{"kanji":"新聞紙","reading":"しんぶんし","meaning":"folha de jornal","level":"B4"},
	{"kanji":"方言","reading":"ほうげん","meaning":"dialeto","level":"B4"},
	{"kanji":"旅行","reading":"りょこう","meaning":"viagem","level":"B3"},
	{"kanji":"旅館","reading":"りょかん","meaning":"pousada em estilo japonês","level":"B4"},
	{"kanji":"日曜日","reading":"にちようび","meaning":"domingo","level":"B3"},
	{"kanji":"日本","reading":"にほん","meaning":"Japão","level":"B2"},
	{"kanji":"日本人","reading":"にほんじん","meaning":"japonês (pessoa)","level":"B2"},
	{"kanji":"日本茶","reading":"にほんちゃ","meaning":"chá japonês","level":"B4"},
	{"kanji":"日本語","reading":"にほんご","meaning":"japonês (idioma)","level":"B2"},
	{"kanji":"日本語学校","reading":"にほんごがっこう","meaning":"escola de japonês","level":"B2"},
	{"kanji":"早い","reading":"はやい","meaning":"cedo","level":"B3"},
	{"kanji":"早口","reading":"はやくち","meaning":"fala rápida","level":"B3"},
	{"kanji":"早朝","reading":"そうちょう","meaning":"de manhã bem cedo","level":"B3"},
	{"kanji":"明るい","reading":"あかるい","meaning":"iluminado; alegre","level":"B2"},
	{"kanji":"明日","reading":"あした","meaning":"amanhã","level":"B2","other_readings":["あす","みょうにち"]},
	{"kanji":"映る","reading":"うつる","meaning":"projetar-se (em tela)","level":"B4"},
	{"kanji":"映画","reading":"えいが","meaning":"filme","level":"B4"},
	{"kanji":"映画館","reading":"えいがかん","meaning":"cinema","level":"B4"},
	{"kanji":"春夏秋冬","reading":"しゅんかしゅうとう","meaning":"as quatro estações","level":"B3"},
	{"kanji":"春雨","reading":"はるさめ","meaning":"chuva de primavera; (nome de prato de comida)","level":"B3"},
	{"kanji":"昼ご飯","reading":"ひるごはん","meaning":"almoço","level":"B3"},
	{"kanji":"昼休み","reading":"ひるやすみ","meaning":"intervalo do almoço","level":"B3"},
	{"kanji":"昼食","reading":"ちゅうしょく","meaning":"almoço","level":"B3"},
	{"kanji":"時計","reading":"とけい","meaning":"relógio","level":"B4"},
	{"kanji":"時間","reading":"じかん","meaning":"tempo; horário","level":"B4"},
	{"kanji":"暑い","reading":"あつい","meaning":"quente (clima)","level":"B3"},
	{"kanji":"暗い","reading":"くらい","meaning":"escuro","level":"B3"},
	{"kanji":"暗記する","reading":"あんきする","meaning":"memorizar; decorar","level":"B3"},
	{"kanji":"暗証番号","reading":"あんしょうばんごう","meaning":"senha","level":"B3"},
	{"kanji":"書く","reading":"かく","meaning":"escrever","level":"B2"},
	{"kanji":"書道","reading":"しょどう","meaning":"arte da caligrafia","level":"B3"},
	{"kanji":"有名","reading":"ゆうめい","meaning":"famoso","level":"B3"},
	{"kanji":"朝ご飯","reading":"あさごはん","meaning":"café da manhã","level":"B3"},
	{"kanji":"朝市","reading":"あさいち","meaning":"feira","level":"B4"},
	{"kanji":"朝食","reading":"ちょうしょく","meaning":"café da manhã","level":"B3"},
	{"kanji":"木曜日","reading":"もくようび","meaning":"quinta-feira","level":"B3"},
	{"kanji":"村長","reading":"そんちょう","meaning":"chefe da aldeia","level":"B4"},
	{"kanji":"来年","reading":"らいねん","meaning":"ano que vem","level":"B2"},
	{"kanji":"東の方","reading":"ひがしのほう","meaning":"direção leste","level":"B4"},
	{"kanji":"東京","reading":"とうきょう","meaning":"Tóquio","level":"B4"},
	{"kanji":"東京都","reading":"とうきょうと","meaning":"capital Tóquio","level":"B4"},
	{"kanji":"東北","reading":"とうほく","meaning":"nordeste","level":"B3"},
	{"kanji":"東口","reading":"ひがしぐち","meaning":"saída leste","level":"B3"},
	{"kanji":"東山さん","reading":"ひがしやまさん","meaning":"Sr. Higashiyama","level":"B3"},
	{"kanji":"東洋","reading":"とうよう","meaning":"Oriente","level":"B4"},
	{"kanji":"東西南北","reading":"とうざいなんぼく","meaning":"pontos cardeais","level":"B3"},
	{"kanji":"校長先生","reading":"こうちょうせんせい","meaning":"diretor de escola","level":"B2"},
	{"kanji":"森川さん","reading":"もりかわさん","meaning":"Sr. Morikawa","level":"B4"},
	{"kanji":"森林","reading":"しんりん","meaning":"selva","level":"B4"},
	{"kanji":"楽しい","reading":"たのしい","meaning":"divertido","level":"B3"},
	{"kanji":"横断歩道","reading":"おうだんほどう","meaning":"faixa de pedestres","level":"B2"},
	{"kanji":"歌う","reading":"うたう","meaning":"cantar","level":"B4"},
	{"kanji":"歌手","reading":"かしゅ","meaning":"cantor","level":"B4"},
	{"kanji":"止まる","reading":"とまる","meaning":"parar-se","level":"B3"},
	{"kanji":"止める","reading":"とめる","meaning":"parar","level":"B3"},
	{"kanji":"正午","reading":"しょうご","meaning":"meio-dia","level":"B2"},
	{"kanji":"歩く","reading":"あるく","meaning":"andar","level":"B4"},
	{"kanji":"歩道","reading":"ほどう","meaning":"calçada","level":"B4"},
	{"kanji":"歯医者","reading":"はいしゃ","meaning":"dentista","level":"B4"},
	{"kanji":"残業","reading":"ざんぎょう","meaning":"hora extra","level":"B4"},
	{"kanji":"毎日","reading":"まいにち","meaning":"todos os dias","level":"B2"},
	{"kanji":"毎月","reading":"まいつき","meaning":"todo mês","level":"B2"},
	{"kanji":"毎朝","reading":"まいあさ","meaning":"todas as manhãs","level":"B3"},
	{"kanji":"毎週","reading":"まいしゅう","meaning":"toda semana","level":"B2"},
	{"kanji":"氏名","reading":"しめい","meaning":"nome [usado em documentos]","level":"B3"},
	{"kanji":"気分","reading":"きぶん","meaning":"estado de espírito","level":"B2"},
	{"kanji":"気持ち","reading":"きもち","meaning":"sensação; sentimento; estado de espírito; humor","level":"B3"},
	{"kanji":"水族館","reading":"すいぞくかん","meaning":"aquário (prédio)","level":"B4"},
	{"kanji":"水泳","reading":"すいえい","meaning":"natação","level":"B2"},
	{"kanji":"注意","reading":"ちゅうい","meaning":"cuidado","level":"B3"},
	{"kanji":"泳ぐ","reading":"およぐ","meaning":"nadar","level":"B2"},
	{"kanji":"洋服","reading":"ようふく","meaning":"roupa no estilo ocidental","level":"B4"},
	{"kanji":"洋食","reading":"ようしょく","meaning":"comida ocidental","level":"B4"},
	{"kanji":"洗う","reading":"あらう","meaning":"lavar","level":"B4"},
	{"kanji":"洗濯","reading":"せんたく","meaning":"lavar roupa","level":"B4"},
	{"kanji":"海外","reading":"かいがい","meaning":"além-mar; estrangeiro","level":"B2"},
	{"kanji":"漢字","reading":"かんじ","meaning":"ideograma","level":"B3"},
	{"kanji":"火事","reading":"かじ","meaning":"incêndio","level":"B3"},
	{"kanji":"無料","reading":"むりょう","meaning":"gratuito","level":"B3"},
	{"kanji":"熱海","reading":"あたみ","meaning":"Atami (nome de cidade do Japão)","level":"B2"},
	{"kanji":"牛乳","reading":"ぎゅうにゅう","meaning":"leite","level":"B4"},
	{"kanji":"牛肉","reading":"ぎゅうにく","meaning":"carne bovina","level":"B4"},
	{"kanji":"生まれる","reading":"うまれる","meaning":"nascer","level":"B2"},
	{"kanji":"生徒","reading":"せいと","meaning":"aluno","level":"B2"},
	{"kanji":"産む","reading":"うむ","meaning":"dar à luz; botar (ovo)","level":"B4"},
	{"kanji":"産物","reading":"さんぶつ","meaning":"produto","level":"B4"},
	{"kanji":"用いる","reading":"もちいる","meaning":"usar; utilizar; empregar","level":"B3"},
	{"kanji":"用事","reading":"ようじ","meaning":"compromisso","level":"B3"},
	{"kanji":"用意する","reading":"よういする","meaning":"preparar [para coisas do dia-a-dia]","level":"B3"},
	{"kanji":"田中家","reading":"たなかけ","meaning":"família Tanaka","level":"B3"},
	{"kanji":"男の子","reading":"おとこのこ","meaning":"menino","level":"B2"},
	{"kanji":"男性","reading":"だんせい","meaning":"rapaz; masculino (banheiro)","level":"B2"},
	{"kanji":"画家","reading":"がか","meaning":"pintor","level":"B4"},
	{"kanji":"病気","reading":"びょうき","meaning":"doente","level":"B3"},
	{"kanji":"病院","reading":"びょういん","meaning":"hospital","level":"B3"},
	{"kanji":"白い","reading":"しろい","meaning":"branco (adj.)","level":"B2"},
	{"kanji":"白米","reading":"はくまい","meaning":"arroz branco","level":"B2"},
	{"kanji":"白紙","reading":"はくし","meaning":"papel em branco","level":"B4"},
	{"kanji":"白鳥","reading":"はくちょう","meaning":"cisne branco","level":"B4"},
	{"kanji":"真っ暗","reading":"まっくら","meaning":"escuridão","level":"B4"},
	{"kanji":"真ん中","reading":"まんなか","meaning":"(no) meio","level":"B4"},
	{"kanji":"着く","reading":"つく","meaning":"chegar","level":"B4"},
	{"kanji":"着る","reading":"きる","meaning":"vestir","level":"B4"},
	{"kanji":"着物","reading":"きもの","meaning":"roupa tradicional japonesa","level":"B4"},
	{"kanji":"知らせる","reading":"しらせる","meaning":"comunicar","level":"B4"},
	{"kanji":"知る","reading":"しる","meaning":"saber","level":"B4"},
	{"kanji":"知人","reading":"ちじん","meaning":"conhecido","level":"B4"},
	{"kanji":"研ぐ","reading":"とぐ","meaning":"afiar","level":"B4"},
	{"kanji":"研修","reading":"けんしゅう","meaning":"estágio","level":"B4"},
	{"kanji":"研究","reading":"けんきゅう","meaning":"pesquisa científica","level":"B4"},
	{"kanji":"祖母","reading":"そぼ","meaning":"avó","level":"B2"},
	{"kanji":"祖父","reading":"そふ","meaning":"avô","level":"B2"},
	{"kanji":"私立大学","reading":"しりつだいがく","meaning":"faculdade particular","level":"B3"},
	{"kanji":"究める","reading":"きわめる","meaning":"dominar (assunto)","level":"B4"},
	{"kanji":"空く","reading":"あく","meaning":"esvaziar-se","level":"B3"},
	{"kanji":"空手","reading":"からて","meaning":"karatê","level":"B3"},
	{"kanji":"空気","reading":"くうき","meaning":"ar","level":"B3"},
	{"kanji":"空港","reading":"くうこう","meaning":"aeroporto","level":"B3"},
	{"kanji":"立つ","reading":"たつ","meaning":"ficar em pé","level":"B3"},
	{"kanji":"立入禁止","reading":"たちいりきんし","meaning":"proibida a entrada","level":"B3"},
	{"kanji":"立派","reading":"りっぱ","meaning":"magnífico","level":"B3"},
	{"kanji":"聞く","reading":"きく","meaning":"ouvir; perguntar","level":"B2"},
	{"kanji":"肉屋","reading":"にくや","meaning":"açougue","level":"B4"},
	{"kanji":"自転車","reading":"じてんしゃ","meaning":"bicicleta","level":"B3"},
	{"kanji":"花火","reading":"はなび","meaning":"fogos de artifício","level":"B2"},
	{"kanji":"花瓶","reading":"かびん","meaning":"vaso de flores","level":"B2"},
	{"kanji":"若者","reading":"わかもの","meaning":"jovem (pessoa)","level":"B4"},
	{"kanji":"英国","reading":"えいこく","meaning":"Grã-Bretanha","level":"B4"},
	{"kanji":"英語","reading":"えいご","meaning":"inglês (idioma)","level":"B2"},
	{"kanji":"茶色","reading":"ちゃいろ","meaning":"marrom","level":"B4"},
	{"kanji":"茶道","reading":"さどう","meaning":"Arte do Chá","level":"B4"},
	{"kanji":"荷物","reading":"にもつ","meaning":"bagagem","level":"B3"},
	{"kanji":"西口","reading":"にしぐち","meaning":"saída oeste","level":"B3"},
	{"kanji":"西川さん","reading":"にしかわさん","meaning":"Sr. Nishikawa","level":"B3"},
	{"kanji":"西洋","reading":"せいよう","meaning":"Ocidente","level":"B4"},
	{"kanji":"見物","reading":"けんぶつ","meaning":"ponto turístico","level":"B3"},
	{"kanji":"見送る","reading":"みおくる","meaning":"acompanhar com os olhos","level":"B4"},
	{"kanji":"親切","reading":"しんせつ","meaning":"gentil","level":"B4"},
	{"kanji":"言う","reading":"いう","meaning":"dizer","level":"B4"},
	{"kanji":"計る","reading":"はかる","meaning":"medir (tempo); calcular","level":"B4"},
	{"kanji":"計画","reading":"けいかく","meaning":"plano; planejamento","level":"B4"},
	{"kanji":"話す","reading":"はなす","meaning":"conversar","level":"B2"},
	{"kanji":"読む","reading":"よむ","meaning":"ler","level":"B2"},
	{"kanji":"読書","reading":"どくしょ","meaning":"leitura","level":"B2"},
	{"kanji":"買い物","reading":"かいもの","meaning":"compras","level":"B3"},
	{"kanji":"買う","reading":"かう","meaning":"comprar","level":"B2"},
	{"kanji":"貸し出す","reading":"かしだす","meaning":"alugar (filme)","level":"B4"},
	{"kanji":"貸す","reading":"かす","meaning":"emprestar","level":"B4"},
	{"kanji":"赤い","reading":"あかい","meaning":"vermelho (adj.)","level":"B2"},
	{"kanji":"赤十字","reading":"せきじゅうじ","meaning":"cruz vermelha","level":"B2"},
	{"kanji":"起きる","reading":"おきる","meaning":"acordar; levantar-se","level":"B4"},
	{"kanji":"起こす","reading":"おこす","meaning":"acordar (alguém)","level":"B4"},
	{"kanji":"起こる","reading":"おこる","meaning":"acontecer","level":"B4"},
	{"kanji":"足りる","reading":"たりる","meaning":"ser suficiente","level":"B3"},
	{"kanji":"足首","reading":"あしくび","meaning":"tornozelo","level":"B3"},
	{"kanji":"転ぶ","reading":"ころぶ","meaning":"tropeçar e cair; levar um tombo","level":"B3"},
	{"kanji":"軽い","reading":"かるい","meaning":"leve","level":"B3"},
	{"kanji":"軽食","reading":"けいしょく","meaning":"refeição leve","level":"B3"},
	{"kanji":"近い","reading":"ちかい","meaning":"perto","level":"B3"},
	{"kanji":"近所","reading":"きんじょ","meaning":"vizinhança","level":"B4"},
	{"kanji":"近道","reading":"ちかみち","meaning":"atalho","level":"B3"},
	{"kanji":"退院する","reading":"たいいんする","meaning":"receber alta (hospital)","level":"B3"},
	{"kanji":"送る","reading":"おくる","meaning":"enviar; acompanhar","level":"B4"},
	{"kanji":"送金する","reading":"そうきんする","meaning":"enviar dinheiro","level":"B4"},
	{"kanji":"運ぶ","reading":"はこぶ","meaning":"carregar; transportar","level":"B3"},
	{"kanji":"運動する","reading":"うんどうする","meaning":"exercitar-se","level":"B3"},
	{"kanji":"運動会","reading":"うんどうかい","meaning":"gincana","level":"B3"},
	{"kanji":"運転","reading":"うんてん","meaning":"direção","level":"B3"},
	{"kanji":"遠い","reading":"とおい","meaning":"longe","level":"B3"},
	{"kanji":"遠足","reading":"えんそく","meaning":"excursão (bate-e-volta)","level":"B3"},
	{"kanji":"選手","reading":"せんしゅ","meaning":"atleta; jogador","level":"B3"},
	{"kanji":"部首","reading":"ぶしゅ","meaning":"radical de kanji","level":"B3"},
	{"kanji":"都会","reading":"とかい","meaning":"metrópole","level":"B4"},
	{"kanji":"都島区","reading":"みやこじまく","meaning":"bairro de Miyakojima","level":"B4"},
	{"kanji":"重い","reading":"おもい","meaning":"pesado","level":"B3"},
	{"kanji":"重ねる","reading":"かさねる","meaning":"empilhar","level":"B3"},
	{"kanji":"野の花","reading":"ののはな","meaning":"flor do campo","level":"B4"},
	{"kanji":"野球","reading":"やきゅう","meaning":"beisebol","level":"B4"},
	{"kanji":"野菜","reading":"やさい","meaning":"verdura; legume","level":"B4"},
	{"kanji":"金魚","reading":"きんぎょ","meaning":"peixinho dourado","level":"B3"},
	{"kanji":"銀行","reading":"ぎんこう","meaning":"banco","level":"B4"},
	{"kanji":"長い","reading":"ながい","meaning":"comprido","level":"B2"},
	{"kanji":"長男","reading":"ちょうなん","meaning":"filho primogênito","level":"B2"},
	{"kanji":"開始する","reading":"かいしする","meaning":"iniciar; começar","level":"B3"},
	{"kanji":"間に合う","reading":"まにあう","meaning":"dar tempo (de fazer algo)","level":"B2"},
	{"kanji":"集まる","reading":"あつまる","meaning":"juntar-se; reunir-se","level":"B3"},
	{"kanji":"集める","reading":"あつめる","meaning":"juntar; reunir","level":"B3"},
	{"kanji":"集中する","reading":"しゅうちゅうする","meaning":"concentrar-se","level":"B3"},
	{"kanji":"電気","reading":"でんき","meaning":"eletricidade","level":"B2"},
	{"kanji":"電気会社","reading":"でんきがいしゃ","meaning":"companhia elétrica","level":"B2"},
	{"kanji":"電話","reading":"でんわ","meaning":"telefone","level":"B2"},
	{"kanji":"電話代","reading":"でんわだい","meaning":"conta de telefone","level":"B3"},
	{"kanji":"電車","reading":"でんしゃ","meaning":"trem","level":"B2"},
	{"kanji":"青い","reading":"あおい","meaning":"azul (adj.)","level":"B2"},
	{"kanji":"青年","reading":"せいねん","meaning":"jovem; juventude","level":"B2"},
	{"kanji":"音楽","reading":"おんがく","meaning":"música","level":"B3"},
	{"kanji":"食料品","reading":"しょくりょうひん","meaning":"produtos alimentícios","level":"B4"},
	{"kanji":"首相","reading":"しゅしょう","meaning":"primeiro ministro","level":"B3"},
	{"kanji":"首都","reading":"しゅと","meaning":"capital federal","level":"B3"},
	{"kanji":"駅員","reading":"えきいん","meaning":"funcionário de estação","level":"B2"},
	{"kanji":"高い","reading":"たかい","meaning":"alto; caro","level":"B2"},
	{"kanji":"高校","reading":"こうこう","meaning":"colegial","level":"B2"},
	{"kanji":"魚市場","reading":"うおいちば","meaning":"mercado de peixe","level":"B3"},
	{"kanji":"黒い","reading":"くろい","meaning":"preto (adj.)","level":"B2"},
	{"kanji":"黒板","reading":"こくばん","meaning":"quadro-negro","level":"B2"},
	{"kanji":"黒鳥","reading":"こくちょう","meaning":"cisne negro","level":"B4"}
];